name: class_plan_flutter
description: "Flutter application to class plan, applying Clean Arch and SOLID"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  bloc: 8.1.4
  collection: 1.19.0
  dio: 5.7.0
  http: 1.2.2
  equatable: 2.0.5
  flutter_bloc: 8.1.6
  get_it: 8.0.1
  intl: 0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: 5.0.0
  mockito:

flutter:
  uses-material-design: true
